cartPage
anastasia-zastela/techmart-ecommerce pull request #10
Opened 2021-10-04 13:57 UTC by Ordx

2021-10-04 17:43 UTC, daviddubliakov requested changes
Отсавил коммент, посмотри!

2021-10-04 17:43 UTC, daviddubliakov commented on client/src/components/common/CartItem/CartItem.js
> +import {
Измени название фалйа на index.jsx

2021-10-04 17:43 UTC, daviddubliakov commented on client/src/components/common/CartItem/CartItem.js
> +    const quantity = 1;
что это? Если не нужно, убери.

2021-10-04 17:44 UTC, daviddubliakov commented on client/src/components/common/CartItem/CartItem.js
> +import {
fixed

2021-10-04 17:45 UTC, daviddubliakov submitted a review, later dismissed

2021-10-04 17:46 UTC, bardovec submitted a review, later dismissed

2021-10-05 08:35 UTC, maxim-petrenko commented on client/src/components/common/CartItem/styles.js
> +export const useStyles = makeStyles((theme) => ({
Мне кажется, что `theme` нигде не используется, этот параметр можно убрать

2021-10-05 08:35 UTC, maxim-petrenko commented on client/src/pages/Cart/styles.js
> +export const useStyles = makeStyles((theme) => ({
Та же история с `theme`, что и в других стилях

2021-10-06 17:44 UTC, Pavlo-Klymchuk approved these changes

2021-10-30 02:14 UTC, closed without merging