styled header and input footer
anastasia-zastela/techmart-ecommerce pull request #3
Opened 2021-09-28 17:31 UTC by Pavlo-Klymchuk

2021-09-29 06:16 UTC, daviddubliakov requested changes

2021-09-29 06:16 UTC, daviddubliakov commented on client/src/components/Header/Header.js
> +                    <button className={classes.buttonSearch}><span>Поиск</span></button>
Почему обычная кнопка?

2021-09-29 06:23 UTC, daviddubliakov commented on client/src/components/Header/Header.js
> +                    <button className={classes.buttonSearch}><span>Поиск</span></button>
test

2021-09-29 06:24 UTC, Pavlo-Klymchuk commented on client/src/components/Header/Header.js
> +                    <button className={classes.buttonSearch}><span>Поиск</span></button>
не подходила стилизация с библиотеки

2021-09-29 06:24 UTC, Pavlo-Klymchuk commented on client/src/components/Header/Header.js
> +                    <button className={classes.buttonSearch}><span>Поиск</span></button>
тест 1

2021-09-29 06:24 UTC, Pavlo-Klymchuk commented on client/src/components/Header/Header.js
> +                    <button className={classes.buttonSearch}><span>Поиск</span></button>
test2

2021-09-29 06:26 UTC, daviddubliakov approved these changes

2021-09-29 06:28 UTC, daviddubliakov requested changes

2021-09-29 06:28 UTC, daviddubliakov commented on client/src/components/Footer/styles.js
>  export const useStyles = makeStyles((theme) => ({
remove theme

2021-09-29 06:37 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/styles.js
>  export const useStyles = makeStyles((theme) => ({
fix

2021-09-29 08:39 UTC, bardovec approved these changes

2021-10-01 06:55 UTC, daviddubliakov requested changes
Нужно изменить ещё несколько важных вещей.

2021-10-01 06:55 UTC, daviddubliakov commented on client/src/components/Footer/Footer.js
> +                    <div style={{ position: 'relative' }}>
Используй вместо div Box из MUI

2021-10-01 06:55 UTC, daviddubliakov commented on client/src/components/Footer/Footer.js
> +        console.log('work');
тут определенно должно быть что-то другое. Зачем тут функция с console.log('work')?

2021-10-01 06:55 UTC, daviddubliakov commented on client/src/components/Footer/Footer.js
>                      <Typography href="#" className={classes.footerTitle}>
это не должен быть Typography - это Link

2021-10-01 06:55 UTC, daviddubliakov commented on client/src/components/Footer/Footer.js
>                      <Typography href="#" className={classes.footerTitle}>
также не везде где ты оставил заглушку #, это плохо. Будут ошибки от линтера. Сделай везде '/' и коммент рядом //TODO

2021-10-01 06:55 UTC, daviddubliakov commented on client/src/components/Footer/styles.js
> +        color: '#A6A6A6',
цвета нужно вынести в папку src/utils в файл UserInterfaceConstants.js и оттуда экспортируй все повторяющиеся больше одного раза boxShadow, colors (вообще все) и другие значения.

2021-10-01 06:55 UTC, daviddubliakov commented on client/src/components/Header/Header.js
> +                    <div className={classes.containerInput}>
тоже Box

2021-10-01 06:55 UTC, daviddubliakov commented on client/src/components/Footer/Footer.js
> +                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
создай папку icons в components и импортни её уже оттуда. Если это какая-то банальная иконка, то просто найди её в material иконках. Возможно, если нету, то нужно будет добавить либу mui/icost-material

2021-10-01 14:01 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/Footer.js
> +                    <div style={{ position: 'relative' }}>
fix

2021-10-01 14:15 UTC, Pavlo-Klymchuk commented on client/src/components/Header/Header.js
> +                    <div className={classes.containerInput}>
fix

2021-10-01 15:19 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/Footer.js
> +                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
fix

2021-10-01 15:51 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/Footer.js
> +        console.log('work');
позже возможно будет добавлен функционал, пока что оставил её чистой и переименовал

2021-10-01 17:32 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/styles.js
> +        color: '#A6A6A6',
fix

2021-10-01 17:47 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/Footer.js
>                      <Typography href="#" className={classes.footerTitle}>
пофиксил, как понял

2021-10-03 09:19 UTC, daviddubliakov requested changes
1. Изменить поле поиска. Оно выглядит вообще не очень. Совет: избавиться от label и сделать только placeholder. Также, можно сделать такой же border-radis как у кнопки.
2. Убрать box-shadow у кнопки "Search". Он выглядит очень странно.
3. Сделать номера телефонов как ссылки типа "tel", чтобы на них можно было кликнуть и сразу позвонить.
4. Также нужно добавить ещё иконки, к примеру, фейсбука и LinkedIn и на все иконки сделай просто, чтобы по нажатию в новом окне открывалась таба с этой социалкой. Просто главная страница.
5. Убрать hover для инпута с email. Потому что он при ховере становится в цвет фона, что делает его непрезентабельным.

2021-10-03 16:25 UTC, Pavlo-Klymchuk commented
fix

2021-10-05 06:54 UTC, daviddubliakov requested changes
1) Нету предыдущих фиксов, которые я просил сделать.
2) У тебя 2 ошибки в инспекторе. Их нужно пофиксить.
![image](https://user-images.githubusercontent.com/62145988/135974144-e0484088-08f9-4ae4-a85e-317dcccf45a7.png)

2021-10-05 08:29 UTC, maxim-petrenko commented on client/src/components/Header/Header.js
> +        const filteredProduct = products.filter(product => {
Если продукт один, то лучше использовать find
```suggestion
        const filteredProduct = products.find(product => {
```

Если он может быть не один, то переменую нужно назвать иначе, не в единственном числе

2021-10-05 08:29 UTC, maxim-petrenko commented on client/src/components/Header/Header.js
> +    const filteredProducts = () => {
(Я понимаю, что это заглушка до момента, когда подключимся к серверу, но всё же)
Я бы назвал эту функцию как-то так
```suggestion
    const searchforProducts = () => {
```
или
```suggestion
    const productSearchHandler = () => {
```

Потому что на следующей строке почти такая же по названию переменная, это немного сбивает с толку

2021-10-05 16:32 UTC, Pavlo-Klymchuk commented on client/src/components/Header/Header.js
> +        const filteredProduct = products.filter(product => {
Это пока нет данных с сервера. после же нужно будет получать список продуктов, чтобы корректно работал поиск, продукт будет не один. В 16 строчне просто написан пустой масив как моковые данные

2021-10-05 16:33 UTC, Pavlo-Klymchuk commented on client/src/components/Header/Header.js
> +    const filteredProducts = () => {
fixed

2021-10-05 16:46 UTC, Pavlo-Klymchuk commented
ошобки пофиксил

2021-10-05 17:27 UTC, maxim-petrenko commented on client/src/components/Header/Header.js
> +        const filteredProduct = products.filter(product => {
Я понял, что пока данных нет, и что используется моковый массив, но тогда лучше назвать переменную **`filteredProducts`** или типа того. В рабочем коде массив с названием `filteredProduct`, содержащие _многие_ товары из сервера, будет смотреться странно

2021-10-05 17:37 UTC, Pavlo-Klymchuk commented on client/src/components/Header/Header.js
> +        const filteredProduct = products.filter(product => {
fixed

2021-10-06 12:52 UTC, bardovec approved these changes

2021-10-08 17:55 UTC, maxim-petrenko approved these changes

2021-10-16 09:53 UTC, merged