Fix/linter warnings annihilation
anastasia-zastela/techmart-ecommerce pull request #5
Opened 2021-09-29 17:23 UTC by maxim-petrenko

As much as possible linter-suggested code issues were resolved, which in several cases involved component refactor. Warning that are left are there due to the linter rules which should be discussed

2021-09-30 08:15 UTC, daviddubliakov requested changes
Написал, что нужно пофиксить. Там потом останется несколько ошибок по export default, их нужно будет пофиксить тоже и ошибки связанные с href в ссылках. Напиши там везде в ссылках просто "/"  и должно пофиксить. В общем, цель все также сделать чистую консоль. Несмотря на то, что есть фиксы - отлично поработал.

2021-09-30 08:15 UTC, daviddubliakov commented on client/.eslintrc
> +    ]
Добавь эти правила. Они нам не нужны и уберут большинство ошибок:
`
"linebreak-style": 0,
"react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
 "react/prop-types": 0`

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/components/Header/Header.jsx
> +import React from 'react';
это должен быть index,jsx - не Header.jsx и потом импортировать его как дефолтный из папки Header

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/components/Footer/Footer.jsx
> +import React from 'react';
это должен быть index,jsx - не Footer.jsx и потом импортировать его как дефолтный из папки Header

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/components/NavBar/NavBar.jsx
> +import React from 'react';
тоже самое что с Header и Footer

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/components/common/Logo/Logo.jsx
> +import React from 'react';
тоже index

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/components/common/ProductCard/ProductCard.jsx
> +import {
тоже index

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/components/common/ProductList/ProductList.jsx
>  import React from 'react';
тоже index

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/components/common/forms/CheckboxWrapper.jsx
>  } from '@material-ui/core';
тоже index

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/index.jsx
>  import ReactDOM from 'react-dom';
должен быть index.js - не .jsx

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/pages/Admin/Admin.jsx
> +import React from 'react';
тоже index

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/pages/Checkout/Checkout.jsx
> +import React from 'react';
тоже index

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/pages/Main/Main.jsx
> +import React from 'react';
тоже index

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/pages/Product/Product.jsx
> +import React from 'react';
тоже index.jsx

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/pages/Products/Products.jsx
> +import React from 'react';
тоже index.jsx

2021-09-30 08:15 UTC, daviddubliakov commented on client/src/pages/Signup/Signup.jsx
> +import React from 'react';
тоже index.jsx

2021-09-30 21:00 UTC, Pavlo-Klymchuk approved these changes

2021-10-03 13:12 UTC, Pavlo-Klymchuk approved these changes

2021-10-05 06:47 UTC, daviddubliakov approved these changes

2021-10-05 07:55 UTC, merged