adding gitignire fix server bugs
anastasia-zastela/techmart-ecommerce pull request #6
Opened 2021-09-30 15:59 UTC by bardovec

2021-09-30 21:02 UTC, Pavlo-Klymchuk submitted a review, later dismissed

2021-10-01 06:40 UTC, daviddubliakov requested changes
Пофикси конфликты

2021-10-01 18:08 UTC, Pavlo-Klymchuk commented on client/src/pages/Admin/Admin.js
> +                Добавить брэнд
ошибка в слове бренд

2021-10-03 08:28 UTC, Pavlo-Klymchuk reviewed
посмотри коментарии

2021-10-03 08:29 UTC, daviddubliakov requested changes
У меня такой error, когда запускаю серве. Переустанавливал на всякий случай модули. Все точно также. У тебя есть эта ошибка? 
![image](https://user-images.githubusercontent.com/62145988/135745977-d4d72109-18c0-4fd9-9bc4-9ce4f625b3ea.png)

Также переименуй ветку на : [BUGFIX]: gitignore and server bugs

2021-10-03 08:32 UTC, Pavlo-Klymchuk requested changes
посмотри коментарии

2021-10-03 08:51 UTC, daviddubliakov requested changes
Оставил  комменты и ещё интересно, что ты на сервере фиксил? Тут особо на сервере кроме пробелов и переносов строк никаких фиксов и нету.

2021-10-03 08:51 UTC, daviddubliakov commented on client/src/pages/Admin/Admin.js
> +            <Button item >
Насколько я знаю, то item есть у Grid, а у Button так делать нельзя, нету пропа item...

2021-10-03 08:51 UTC, daviddubliakov commented on client/src/pages/Admin/styles.js
> +
если это "на свякий случай" или "когда будет нужно", то лучше убрать и добавить, когда будет необходимость

2021-10-03 11:13 UTC, Pavlo-Klymchuk approved these changes

2021-10-03 13:14 UTC, daviddubliakov approved these changes

2021-10-03 13:14 UTC, merged