Product details Tabs
anastasia-zastela/techmart-ecommerce pull request #9
Opened 2021-10-01 19:10 UTC by purplehazzzze

2021-10-02 14:52 UTC, Pavlo-Klymchuk approved these changes

2021-10-03 13:51 UTC, daviddubliakov requested changes
Оставил комментарии, убери yarn.lock и добавь его вообще в .gitignore.

2021-10-03 13:51 UTC, daviddubliakov commented on client/src/components/common/ProductDetailsTabs/ProductDetailsTabs.js
> +    <>
Выравнивание нужно пофиксть

2021-10-03 13:51 UTC, daviddubliakov commented on client/src/components/common/ProductDetailsTabs/ProductDetailsTabs.js
> +    const classes = useStyles();
classes перед стейтами должен быть оглашен

2021-10-03 13:51 UTC, daviddubliakov commented on client/src/components/common/ProductDetailsTabs/ProductDetailsTabs.js
> +
отдели импорты из библиотек, компоненты и стили:

import React, {useState} from 'react';
import {Paper} from "@material-ui/core";

import CenteredTabs from "./Tabs/Tabs";
import Reviews from "./Tabs/Reviews/Reviews";

import useStyles from "./styles";

2021-10-03 13:51 UTC, daviddubliakov commented on client/src/components/common/ProductDetailsTabs/ProductDetailsTabs.js
> +import React, {useState} from 'react';
файл должен называтся index и тогда ты може обращатся сюда просто: 
import PoductDetailsTabs from "@components/common/ProductDetailsTabs"; (как пример)

2021-10-03 13:51 UTC, daviddubliakov commented on client/package.json
> +    "@emotion/react": "^11.4.1",
Зачем добавлять @emotion?

2021-10-03 13:51 UTC, daviddubliakov commented on client/src/components/common/ProductDetailsTabs/ProductDetailsTabs.js
> +    const [desc, setDesc] = useState(true);
Назовни нормально стейты, к примеру, я не понимаю, что они делают. Reviewers - понятно.

2021-10-03 13:51 UTC, daviddubliakov commented on client/src/components/common/ProductDetailsTabs/ProductDetailsTabs.js
> +import CenteredTabs from "./Tabs/Tabs";
почему Centered?

2021-10-03 17:07 UTC, purplehazzzze commented on client/src/components/common/ProductDetailsTabs/ProductDetailsTabs.js
> +import React, {useState} from 'react';
т.е. все компоненты переименовать на Индекс? я в прнципе к нему так и обращаюсь

2021-10-09 11:50 UTC, Pavlo-Klymchuk commented on client/src/components/common/ProductDetailsTabs/Tabs/Reviews/index.js
> +
пару пустых строк я бы убрал

2021-10-31 11:47 UTC, Pavlo-Klymchuk approved these changes

2021-11-01 11:07 UTC, daviddubliakov approved these changes

2021-11-03 15:38 UTC, Pavlo-Klymchuk requested changes
конфликты

2021-11-03 19:03 UTC, purplehazzzze commented
> конфликты

пофиксил

2021-11-04 16:21 UTC, Pavlo-Klymchuk approved these changes

2021-11-05 08:07 UTC, merged